# -*- coding: utf-8 -*-
"""Copia de Introducción a la programación con Python - FFRO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11kYmJHEgjnxUsmPMDcugULlNzDEY0o9E

# Antes de comenzar
## Para personalizar este cuaderno, es necesario que sigas las siguientes instrucciones:
### 1 - Dirigite al menu 'Archivo' y luego selecciona 'Guardar una copia en Drive'
### 2 - En la ventana emergente, selecciona 'Abrir en pestaña nueva'. Esto abrirá la copia de trabajo en una pestaña nueva.
### 3 - En la nueva pestaña aparecerá la copia que permanecerá almacenada en tu cuenta de Google Drive. En este cuaderno podras hacer todos los cambios que desees.

## Librerias
"""

!pip install qrcode[pil] -q

import qrcode

# Crear un código QR
qr = qrcode.QRCode(version=1, box_size=10, border=5)
qr.add_data('https://www.python.org')
qr.make(fit=True)

# Crear una imagen del código QR
img = qr.make_image(fill_color="blue", back_color="white")

# Guardar la imagen
img.save("python_qr.png")

print("Código QR generado y guardado como 'python_qr.png'")

!pip install gradio -q

import gradio as gr

def saludo(nombre, intensidad):
  return "Hola, " + nombre + "!" * int(intensidad)

demo = gr.Interface(
  fn=saludo,
  inputs=["text", "slider"],
  outputs=["text"],
)

demo.launch()

"""# Introducción a la programacion con Python

### En esta notebook vamos a revisar los conceptos básicos de Python que necesitas para comprender fundamentos de progamación, tipos de datos y operaciones y seguir avanzando en desarrollo de programas.

I. Introducción a la programación con Python

II. Tabla de Contenidos

    I. Python

III. IDEs

        I. Thonny
        II. Visual Studio Code
        
IV. Hola Jupyter!

V. Variables y tipos de datos

    I. Numéricos
    II. Operaciones numéricas - Divisiones
    III. Booleanos
        I. Operaciones lógicas

VI. Casos y distintas formas de aplicacion

    I. Strings
    II. Listas
        I. Indexing y slicing en listas
        II. Otras operaciones y métodos
    III. Diccionarios
    IV. Condicionales
    V. Bucles o Loops
        I. For loop
        II. While loop

VII. Funciones

VIII. Montar unidad de Google Drive

IX. Librerias

## Python

- Elegante, sencillo
- Comunidad y accesibilidad
- Desarrollos de estado del arte
- Flexibilidad "full stack"
- Multi-paradigma
"""

import this

"""#### El Zen de Python, por Tim Peters

- Bello es mejor que feo.
- Explícito es mejor que implícito.
- Simple es mejor que complejo.
- Complejo es mejor que complicado.
- Plano es mejor que anidado.
- Espaciado es mejor que denso.
- La legibilidad es importante.
- Los casos especiales no son lo suficientemente especiales como para romper las reglas.
- Aunque la practicidad vence a la pureza.
- Los errores nunca deberían pasar silenciosamente.
- A menos que se silencien explícitamente.
- Frente a la ambigüedad, rechaza la tentación de adivinar.
- Debería haber una, y preferiblemente solo una, manera obvia de hacerlo.
- Aunque esa manera puede no ser obvia al principio a menos que seas holandés.
- Ahora es mejor que nunca.
- Aunque nunca es a menudo mejor que *ahora* mismo.
- Si la implementación es difícil de explicar, es una mala idea.
- Si la implementación es fácil de explicar, puede ser una buena idea.
- Los espacios de nombres son una gran idea, ¡hagamos más de esos!

# IDEs

<img src='https://thonny.org/img/screenshot.png'></img>

<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Visual_studio_code_updated.png/1200px-Visual_studio_code_updated.png'></img>

### Variables

### Las variables son contenedores que almacenan datos. Puedes usar variables para guardar información y trabajar con ella.

Existen distintos tipos:

- int: entero
- float: punto flotante
- string: cadena de caracteres
- bool: booleano, 0, 1, True o False

Y estructuras de datos, como:

  - list: lista de elementos (de cualquier tipo, incluida otra lista)
  - dict: "diccionario", conjunto de pares llave:valor
  
Veamos un primer ejemplo
"""

variable1 = "naranja"  # Esto es una variable de cadena (string)

type(variable1)

variable2 = "2"

type(variable2)

variable3 = float(input("Ingresá un número: "))

type(variable3)

print(variable3)

print(variable1 + variable2)

numero_a = int(input("Ingresá un número: "))

type(numero_a)

numero_b = int(input("Ingresá otro número: "))

print(numero_a + numero_b)

numero_c = numero_a + numero_b

type(numero_c)

"""Declaramos una variable llamada *primera_variable* asignándole el valor de "Hola mundo!". La **función print** toma entre paréntesis esa variable y muestra el valor en pantalla."""

print("Hola Mundo!")

"""Declaramos una variable llamada *input_de_usuario* que pedirá al usuario que ingrese un dato. *input_de_usuario* imprime el valor de la variable"""

nombre_usuario = input("Ingresá tu nombre: ") # Esto es una variable que recibe entrada del usuario

#print(miVariable2)
print(nombre_usuario)

"""# Definimos dos variables numéricas

### Y analizamos distintas operaciones posibles entre ellas
"""

x = 2

y = 10

# Operaciones aritméticas
suma = x + y  # Suma
resta = x - y  # Resta
multiplicacion = x * y  # Multiplicación
division = x / y  # División
division_entera = x // y  # División entera (descarta el residuo)
resto = x % y  # Módulo (el resto de la división)

# Operaciones de potenciación
potencia = x ** 2  # Potencia (num1 elevado a la n)

# Imprimimos los resultados de las operaciones
print("Suma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)
print("División:", division)
print("División entera:", division_entera)
print("Resto:", resto)
print("Potencia:", potencia)

"""La **función** _type_ recibe de **argumento** una **variable** y **devuelve** su tipo"""

type(x), type(y)

numero1 = 10.0
type(numero1)

texto = "Hola"
type(texto)

"""Intentemos la siguiente suma..."""

5 + int("10")

"""¿Qué paso?

Si **convertimos** el string "10" a tipo int
"""

edad_usuario = float(input("Ingresá tu edad: "))

type(edad_usuario)

"""## En el siguiente codigo veremos variables booleanas, las cuales solo pueden contener dos valores ('True', 'False').
###  Podes probar distintos operadores de comparación (==, !=, <, >, <=, >=) y analizar como fnciona el siguiente codigo:
"""

# Operaciones de comparación
igual = x == y  # Igual a
diferente = x != y  # Diferente de
mayor = x > y  # Mayor que
menor = x < y  # Menor que
mayor_igual = x >= y  # Mayor o igual que
menor_igual = x <= y  # Menor o igual que

# Imprimimos los resultados de las operaciones
print("Igual a:", igual)
print("Diferente de:", diferente)
print("Mayor que:", mayor)
print("Menor que:", menor)
print("Mayor o igual que:", mayor_igual)
print("Menor o igual que:", menor_igual)

print("El valor de X es:", x)
print("El valor de Y es:", y)

print(f"El valor de X es: {x} y el valor de Y es: {y}")

dato_usuario = input("Ingrese un dato: ")

if dato_usuario == "uno" or dato_usuario == "1":
  print("el dato ingresado es uno")
else:
  print("el dato ingresado no es uno")

numero1 = float(input("Ingresá un numero: "))
numero2 = float(input("Ingresá otro numero: "))

operacion = int(input("""¿Qué operacion matematica queres hacer?
                          1 (SUMA)
                          2 (RESTA)
                          """))

if operacion == 1:
  print(f"El resultado de la suma de {numero1} y {numero2} es {numero1 + numero2}")
elif operacion == 2:
  print(f"El resultado de la resta de {numero1} y {numero2} es {numero1 - numero2}")
else:
  print("Ingresaste una operacion no valida")

help(print)

print?

"""## Strings <a name="section-4"></a>"""

"dos strings se pueden " + "concatenar"

print("dos strings se pueden", "concatenar")

a = 1

b = 2

print(type(a))

"""Podemos acceder a ellos mediante **índices**. Los mismos funcionan para cualquier **iterable**, que es un objeto con muchos elementos que son accesibles secuencialmente. Podemos usar los índices para acceder a una posición determinada, pasándola entre corchetes [posición]. Es IMPORTANTE mencionar que en Python la primera posición tiene el índice 0 (y no 1)."""

texto = "programación en python"

texto[6]

print(f"El primer caracter es: {texto[0]}")
print(f"El décimo caracter es: {texto[9]}")

"""También podemos usar los índices para traer más de un elemento al mismo tiempo, usando el **slicing**. El slicing lleva tres parámetros: comienzo (start), final (stop) e intervalo o paso (step).

- El parámetro comienzo (start) indica la primera posición incluida en la selección, por default es 0.

- El parámetro final (stop) es la primera posición que NO va a estar incluída, por default se incluyen todos los elementos.

- El parámetro intervalo o paso (step), es optativo e indica el tamaño del paso entre seleccionar un elemento y el siguiente, por default el paso es 1. El paso también puede ser negativo, en este caso contamos desde el final hacia el comienzo, esto es muy útil para dar vuelta los strings...

    
    [comienzo : final : intervalo] (en inglés es [start : stop : step] )
    
    
El intervalo que se recibe es semi-abierto (indice_primero, indice_segundo], es decir se incluye el primero y no el segundo valor. Se admiten números negativos, que contabilizan desde el final.
"""

texto[:]

texto[:3]

texto[1:4]

texto[::-1]

"""Veamos algunos otros métodos de los strings"""

texto.upper()

texto.title()

texto.split() # Devuelve una lista, de ésto vamos a hablar a continuación

"""Otras formas de combinar variables y texto...

Rellenamos un string con **.format(query, modales)**:
"""

tema = 'intro a Python'
modales = 'por favor'

'Dame información de {} si esta disponible, {}'.format(modales, tema)

print(f"Dame información de {tema.upper()} si esta disponible, {modales}")

#Otra manera
print(f'Dame información de {tema.upper()} si esta disponible, {modales}')

"""Otros métodos a mencionar son:"""

texto

texto.replace(' ', '_')

"   quitando espacios  ".strip()

"1000".isdigit()

"""##Recapitulación"""

# Introduciendo más variables y sustituciones
nombre = input('Escriba aqui un nombre: ')
edad = input('Escriba aqui una edad en numeros: ')
direccion = input('Escriba aqui una direccion con su numero ')
informacion = "Nombre: {}\nEdad: {}\nDirección: {}".format(nombre, edad, direccion)
print(informacion)

# Definimos dos variables con nombres descriptivos
a = 2
b = 2

# Introducimos una variable booleana para verificar si a es igual a b
son_iguales = (a == b)

# Utilizamos el método str.format() para formatear una cadena de manera más legible
concatenacion = "{} y {}".format(a, b)

# Imprimimos la cadena formateada
print(concatenacion)

# Usamos una variable booleana en una condición
if son_iguales:
    print("Las dos variables son iguales.")
else:
    print("Las dos variables son diferentes.")

"""## Listas <a name="section-6"></a>

Las listas son un conjunto de elementos ordenados. Estos elementos pueden ser de cualquier tipo, incluyendo otras listas. Veamos algunas operaciones con ellas.

"""

amigos = ['Mateo', 'Nico', 'Claudia', 'Ernestina', 'Paola']

amigas = ("Tamy", "Claudia", "Caro")

"""### Indexing y slicing en listas

De la misma forma que con los strings en el contexto de la listas generalmente hablamos de indexación o acceso por índice a la acción de encontrar un valor según su posición en la lista.

Importantísimo (sí, ¡una vez más!): En Python el primer elemento se indexa con el valor 0. Es decir, si queremos el primer valor de una lista tenemos que llamar a la posición 0.
"""

amigos[0]

"""Además, el último elemento se indexa como -1, el siguiente -2 y así sucesivamente. Entonces para acceder al último elemento:"""

amigos[-1]

"""Además, podemos acceder a varios elementos en simultáneo, usando el slicing de la misma manera que con strings.

El slicing aplicado a una lista nos devuelve una lista.

Veamos algunos ejemplos:
"""

amigos[:] # arranco en 0 hasta el final, con el paso default (1)

amigos[:1] # arranco en 0 y el primero sin incluir es el 1, con el paso default (1)

amigos[:-1] # excluímos el último elemento

amigos[::2] # salteamos un elemento a la vez

# lista basica en Python
X = [2, 5, 7, -2, 0, 8, 13]

# las listas pueden contener muchos tipos de datos
Y = [99, 'Alice', -14.2903, 'Bob', [1,2,3], 50]

# las listas tienen indice 0, por lo tanto en indice 2 es el elemento 3 de la lista X
print(X[2])
print(Y[1], Y[3])

"""### Otras operaciones y métodos

Agregar un nuevo elemento:
"""

amigos.append('Chicharito')
print(amigos)

amigos = amigos + ['Chicharito']

amigos

x = 10

x

x = x + 3

x

"""Sumamos otra lista:"""

amigos = amigos + ['Pipi', 'Toto']
print(amigos)

"""Unir una lista con un separador dado:"""

ejemplo = ['valor1', 'valor2', 'valor3']
'#'.join(ejemplo)

" ".join(["hola", "qué tal"])

"""Borrado por valor:"""

amigos

amigos.remove('Chicharito')
print(amigos)

"""Borrado por índice:"""

del amigos[4]
print(amigos)



edades = [30, 40, 38, 30, 37]

"""Devuelve un elemento y lo borra de la lista:"""

valor = amigos.pop(0)

valor

amigos

"""Cantidad de apariciones:"""

print(edades.count(30))

"""Largo de la lista:"""

print(len(edades))

"""Ordenar la lista:"""

sorted(edades)

"""Sumar el total"""

print(sum(edades))

"""Minimo"""

print(min(edades))

"""Maximo"""

print(max(edades))

"""## Diccionarios <a name="section-8"></a>

Los diccionarios consisten en estructuras que contienen pares de una **llave** y un **valor**. Los elementos NO están ordenados, con lo cual no se puede acceder por posición ni slicing.

Veamos un ejemplo
"""

dnis = {'Herrera':32676585, 'Guzmán':9564787,
        'Pérez':5676898, 'Hernández':40565999,
        'Abraham':28375814,
       "soy_una_llave":"soy_un_valor"}

dnis

"""Sin embargo, sí podemos acceder a un elemento por su llave. Accedemos al valor de "Abraham"
"""

dnis['Abraham'] # noten que se usa la misma notación que con las listas

"""¿Qué pasa si tratamos un diccionario como una lista?"""

dnis[0]

"""Tenemos un error, tratemos de interpretarlo: KeyError se refierre a que no existe una llave (Key) a la que se trató de acceder. En este caso la llave que se trató de acceder es 0.

Podemos ver todas las llaves:
"""

dnis.keys()

"""Traer todos los pares de elementos:"""

dnis.items()

"""Y utilizar los mismos métodos para borrar y extrar como en las listas:"""

dnis.pop('Herrera')

"""Los diccionarios tienen longitud, de la misma forma que las listas y string"""

len(dnis)

"""## Condicionales <a name="section-9"></a>

El condicional tiene la siguiente sintáxis:

    if CONDICIÓN:
        código1
    elif CONDICIÓN2:
        código2
    else:
        código3
        
Donde la condición es un operador que devuelve un objeto de tipo booleano. La **indentación** del código define qué parte se incluye como condicional.

El término "elif" viene de "else if". La condición sólo se evaluará si la condición del "if" no se cumple.
"""

numero_secreto = 56 # Cambiamos este valor para jugar

numero_usuario = int(input("Introduce un número: "))

if numero_usuario == numero_secreto:
  print("¡Felicidades! Adivinaste el número secreto.")
elif numero_usuario < numero_secreto:
  print("El número secreto es mayor que tu número.")
else:
  print("El número secreto es menor que tu número.")

print("Intenta adivinar el número secreto de nuevo.")

"""## Bucles o Loops

Los bucles son un tipo de sentencia donde se realiza el código contenido repetidamente. Existen dos tipos. En el bucle **for**, se **itera** o recorre un conjunto de elementos actuando por cada uno de ellos. En el bucle **while** se itera hasta que se cumple una condiciónn de corte.

### For loop
"""

for n in [1,2,'3']:
    print(f'EL tipo es {n*2} {type(n*2)}')

lista = [1,2,3,4,5]

for numero in lista:
    print(numero * 2)

for _ in range(10):
    print(_)

"""Si pasamos dos parámetros, estamos pasando el start y el stop, el primer valor es el "start" y el segundo el "stop"."""

for n in range(0,5):
    print(n)

"""Noten que el valor de start se incluye y el de stop no:"""

for n in range(1, 6): # esto nos da el mismo resultado que un par de celdas más arriba
    print(n * 2)

"""Por último, el tercer parámetro es el step..."""

for n in range(1, 11, 2):  # Incrementando de a 2
    print(n)

"""### While loop

Los bucles **while** se definen con una condición, y el código contenido se ejecuta mientras la misma evalue como True. Es importante definir correctamente cuándo la condición pasa de True a False, si no lo hacemos podemos dejar corriendo un programa infinitamente sin que corte. Si eso llega a suceder tienen un botón de stop arriba en la notebook.
"""

contador = 0

while contador < 20:
    contador += 1 # esto equivale a count = count + 1
    print(contador)

"""También agreguemos la función **range** a nuestro repertorio. La función range consta de tres parámetros importante: start, stop, step. Si pasamos un sólo parámetro, estamos pasando el "stop" y tomamos 0 como valor default de "start". Del mismo modo que cuando vimos listas, el stop no está incluído y el step por default es 1.

Veamos cómo funciona:

### Usando un bucle for para imprimir saludos a cada nombre en la lista

#### El %s en la cadena es un marcador de posición que se utilizará para insertar el valor de n en el mensaje de saludo. El operador % se usa para formatear la cadena, donde %s se reemplazará por el valor de n en cada iteración.
"""

nombres = ['Alicia', 'Bob', 'Carol', 'David', 'Juancito']
for n in nombres:
    print('Hola %s' % n)

"""Una forma más actual y legible de escribir este código es utilizar literales de cadena f-strings (disponibles a partir de Python 3.6). Esto simplifica el formato de cadena y hace que el código sea más claro:"""

nombres = ['Alicia', 'Bob', 'Carol', 'David', 'Juancito']
for nombre in nombres:
    print(f'Hola {n}')

"""***f'Hola {n}*** es una f-string que interpola automáticamente el valor de ***n*** en la cadena. Esto hace que el código sea más conciso y fácil de entender.

## Funciones
### Las funciones son bloques de código reutilizables que realizan una tarea específica.
"""

print("Hola Mundo!")

def saludo(nombre):
    print('Hola ' + nombre + '!')

saludo("Martin")
saludo("Kevin")

def mi_funcion(miArgumento):
    print('Buenas tardes ' + miArgumento.upper() + '!')

mi_funcion("Gustavo")

a = 10
b = 20

def otraFuncion(argumento):
    print(str(a) + ' y ' + str(b) + ' son variables')

otraFuncion("argumento")

"""#Datos

El tipo de datos que más frecuentemente vamos a utilizar en este curso es el dataframes de Pandas. Un dataframe esencialmente es una tabla con columnas y filas indexadas, de forma tal que podemos acceder fácilmente a filas mediante el índice. También podemos unir, separar o filtrar dataframes trabajando sobre el índice. En general, los dataframes le van a resultar bastante familiares a quienes sepan SQL.

Los dataframes pueden tener datos no heterogéneos y además son objetos con métodos útiles para extraer información de forma rápida (por ejemplo, computar histogramas de valores). También es posible convertirlos a arrays de Numpy si así lo necesitamos, aunque no lo vamos a hacer a menos que sea realmente necesario.

Una forma de construir dataframes es a partir de diccionarios, de forma tal que asignamos una lista a cada llave, que representa una columna del dataframe:
"""

datos = {'alumno': ['Zutano', 'Mengano', 'Pepe' ,'Fulanito, Cosme', 'Maria'], 'primer parcial': [7, 8,7,4, 10], 'segundo parcial': [10,9,4,10,10], 'observaciones':['ninguna','libre','ninguna','libre','oyente'], 'DNI':[23000000, 12389100, 99999, 1001,30406011]}

import pandas as pd

df = pd.DataFrame(datos)

df

"""Vemos que las filas están identificadas con números (0,1,2). Esos números corresponden al índice (index). Podemos obtener las columnas y el índice de un dataframe como listas usando los siguientes métodos:"""

print(list(df.columns))
print(list(df.index))

"""Podemos ademas seleccionar una columna del dataframe como si se tratase de un diccionario. El objeto resultante se llama "series":"""

print(type(df))
print(df['alumno'])
print(type(df['alumno']))

"""Para obtener files en vez de columnas, podemos usar el método df.loc con una lista de los índices que queremos acceder:"""

df.loc[2]

"""O bien:"""

df.loc[2:4]