# -*- coding: utf-8 -*-
"""Copia de guia_git_github.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1beDHzedT64FEbqm6NSyMzpUrQN672U0E

# Guía Zero to Hero: Git y GitHub
## Organización del repositorio personal de cursada

**Matías Barreto**  
Especialista en Interactividad y Nuevos Medios  
[matiasbarreto.com](https://matiasbarreto.com)

## Introducción

Esta guía te acompaña desde la configuración inicial de Git y GitHub hasta la publicación de tu primer repositorio de cursada.

Está pensada para estudiantes de cualquier materia o curso de programación, tecnología o ciencia de datos que todavía no trabajaron con control de versiones o que necesitan ordenar su flujo de trabajo.

No necesitás experiencia previa. El objetivo no es solo subir archivos: vas a construir un repositorio claro, consistente y útil para seguir la materia, entregar actividades y conservar un registro de tu producción a lo largo de la cursada.

## Objetivos de aprendizaje

Al terminar esta guía vas a poder:

1. Diferenciar qué hace **Git** y qué hace **GitHub**.
2. Configurar tu identidad en Git para empezar a versionar archivos.
3. Crear un repositorio en GitHub con la nomenclatura correcta para tu curso.
4. Organizar la estructura de temas y semanas en tu repositorio.
5. Subir notebooks, archivos de código, imágenes, PDF y diapositivas de forma ordenada.
6. Compartir enlaces de entrega desde GitHub sin comprimir archivos ni habilitar permisos extra en Google Colab.
7. Resolver los problemas más comunes del flujo básico de trabajo.

## Parte 1: Qué son Git y GitHub

**Git** es un sistema de control de versiones. Te permite registrar cambios en tus archivos, volver a estados anteriores y trabajar de manera ordenada.

**GitHub** es una plataforma que aloja repositorios Git en la web. Funciona como espacio de publicación, respaldo y entrega.

En tus cursos, tu repositorio personal cumple varias funciones al mismo tiempo:

- organiza tus materiales tema a tema o semana a semana;
- conserva notebooks y otros archivos importantes;
- permite a los docentes revisar tu trabajo;
- simplifica las entregas, porque compartís enlaces ya publicados en GitHub.

En otras palabras: tu repositorio no es un depósito improvisado de archivos. Es tu carpeta de cursada versionada.

## Parte 2: Convención para nombrar el repositorio

El nombre del repositorio debe respetar esta estructura:

```text
apellido-nombre-materia-cuatrimestre-anio
```

Ejemplos correctos:

- `perez-ana-python-1c-2026`
- `gomez-juan-bd-2c-2027`
- `lopez-maria-ia-1c-2026`

Componentes del nombre:

| Parte | Significado | Ejemplo |
|---|---|---|
| `apellido` | tu apellido | `perez` |
| `nombre` | tu nombre | `ana` |
| `materia` | nombre corto de la materia o curso | `python` o `bd` |
| `1c` o `2c` | período o cuatrimestre | `1c` |
| `año` | año lectivo | `2026` |

Reglas prácticas:

- usá **minúsculas**;
- usá **guiones medios** (`-`) en lugar de espacios;
- no uses tildes;
- si tu nombre o apellido tiene `ñ`, reemplazala por `n` simple;
- mantené siempre el mismo criterio de escritura.

## Parte 3: Estructura interna del repositorio

Dentro del repositorio, la organización debe seguir un orden temático o semanal simple y claro.

Sugerimos crear una carpeta por semana o tema usando tres dígitos correlativos seguidos de un nombre descriptivo corto en minúsculas y separado por guiones bajos. De esta forma, tus archivos y prácticas quedarán automáticamente ordenados cronológicamente y por tema, tanto en tu computadora como en GitHub.

Formato del nombre de la carpeta:

```text
numero_tema
```

Ejemplos de carpetas por semana/tema:

| Carpeta | Uso o Tema principal |
|---|---|
| `001_intro_python` | Primera semana: Introducción al lenguaje Python |
| `002_estructuras_control` | Segunda semana: Condicionales y bucles |
| `003_funciones_y_modulos` | Tercera semana: Modularización de código |

Ejemplo de estructura completa en el repositorio:

```text
perez-ana-python-1c-2026/
├── 001_intro_python/
│   ├── cuaderno_ejercicios.ipynb
│   └── apuntes_clase.pdf
├── 002_estructuras_control/
│   └── practica_condicionales.ipynb
└── 003_funciones_y_modulos/
    └── laboratorio_funciones.ipynb
```

No hace falta definir desde ahora cuántos temas tendrá tu curso. Lo importante es que mantengas siempre el mismo patrón de numeración de tres dígitos (`001`, `002`, `003`...) seguido de una breve descripción del tema a medida que avances en las clases.

## Parte 3.1: Regla clave sobre carpetas vacías

Git **no versiona carpetas vacías**. Esto significa que, si creás una carpeta pero no guardás ningún archivo adentro, esa carpeta no aparecerá en GitHub.

Tenés dos caminos válidos:

1. Crear las carpetas a medida que vas teniendo material para guardar.
2. Dejar la estructura preparada y agregar un archivo de apoyo, por ejemplo `README.md` o `.gitkeep`.

Si querés dejar la carpeta del primer tema (`001_intro_python`) armada desde el inicio, podés usar este esquema en la terminal:

```bash
mkdir -p 001_intro_python
touch 001_intro_python/.gitkeep
```

Si trabajás desde el explorador de archivos y no desde la terminal, el criterio es el mismo: cada carpeta vacía necesita al menos un archivo (como un archivo vacío llamado `.gitkeep`) para quedar registrada en Git.

## Parte 4: Preparación del entorno

Antes de crear tu repositorio, prepará estas tres cosas:

1. **Instalar Git** desde [git-scm.com](https://git-scm.com/downloads).
2. **Crear tu cuenta en GitHub** desde [github.com/signup](https://github.com/signup).
3. **Elegir una ubicación local de trabajo** en tu computadora, por ejemplo una carpeta llamada `Repositorios` o `Cursada`.

Recomendación de trabajo:

- si usás Windows, instalá Git con **Git Bash** y **Git Credential Manager**;
- usá el mismo correo en Git y en GitHub siempre que sea posible;
- para tu cursada, conviene que tu repositorio sea **público**, salvo indicación docente en contrario. De ese modo, el enlace de entrega funciona sin pedir permisos adicionales al docente.

Para verificar que Git quedó instalado correctamente, abrí la terminal y ejecutá:

```bash
git --version
```

## Parte 4.1: Configuración de identidad en Git

Git necesita saber quién registra los cambios. Configuralo una sola vez en tu computadora.

Reemplazá los datos de ejemplo por los tuyos:

```bash
git config --global user.name "Tu Nombre y Apellido"
git config --global user.email "tu-correo@ejemplo.com"
git config --global init.defaultBranch main
```

Para revisar la configuración actual:

```bash
git config --global --list
```

Si en algún momento Git te muestra un error parecido a `Author identity unknown`, casi siempre se resuelve con esta configuración.

## Parte 5: Crear el repositorio en GitHub

La ruta recomendada para esta guía es crear primero el repositorio en GitHub y después clonarlo a tu computadora.

Pasos:

1. Entrá a GitHub.
2. Hacé clic en **New repository**.
3. Escribí el nombre exacto con la convención recomendada.
4. Elegí visibilidad **Public** si no te indicaron otra cosa.
5. Marcá la opción **Add a README file** para arrancar con una rama `main` ya creada.
6. Creá el repositorio.

Ejemplo:

```text
perez-ana-python-1c-2026
```

Antes de continuar, revisá dos veces el nombre. Corregirlo al principio es muy fácil; corregirlo tarde genera trabajo innecesario.

## Parte 6: Clonar el repositorio en tu computadora

Una vez creado el repositorio remoto, copiás su contenido a tu máquina local con `git clone`.

En GitHub:

1. Abrí tu repositorio.
2. Hacé clic en **Code**.
3. Copiá la URL HTTPS.

En la terminal, ubicate en la carpeta donde querés trabajar y ejecutá:

```bash
git clone https://github.com/tu-usuario/perez-ana-python-1c-2026.git
cd perez-ana-python-1c-2026
```

A partir de ese momento, todo lo que guardes dentro de esa carpeta puede versionarse con Git.

Si ya habías empezado a trabajar en una carpeta local sin clonar el repositorio, también es posible vincularla después. Sin embargo, para comenzar, este flujo suele ser el más claro y el menos propenso a errores.

## Parte 7: Crear la estructura inicial de temas y carpetas

Ya dentro del repositorio clonado, creá la estructura de trabajo. Podés empezar por el primer tema `001_intro_python` y después replicar el patrón para las clases sucesivas.

Ejemplo en la terminal (Git Bash o Terminal de macOS/Linux):

```bash
mkdir -p 001_intro_python
touch 001_intro_python/.gitkeep
```

Si querés dejar también el segundo tema preparado:

```bash
mkdir -p 002_estructuras_control
touch 002_estructuras_control/.gitkeep
```

Alternativa manual:

- creá las carpetas desde el explorador de archivos de tu sistema;
- agregá después al menos un archivo dentro de cada carpeta que quieras publicar (por ejemplo, un `.gitkeep` si está vacía);
- mantené la nomenclatura sugerida de tres dígitos correlativos seguidos de un nombre descriptivo en minúsculas y separado por guiones bajos (ej. `001_nombre_tema`). Evitá nombres inconsistentes para que tu repositorio quede ordenado automáticamente.

## Parte 8: Primer flujo completo de Git

Una vez creada la estructura inicial, llega el momento de registrar y publicar los cambios.

Ejecutá estos comandos dentro del repositorio:

```bash
git status
git add .
git commit -m "Crear estructura inicial del repositorio"
git push origin main
```

Qué hace cada paso:

- `git status` muestra qué cambió;
- `git add .` prepara los archivos para el commit;
- `git commit -m "..."` guarda un punto de control local con un mensaje explicativo;
- `git push origin main` publica esos cambios en GitHub.

Cuando termines, actualizá la página del repositorio en GitHub y verificá que la estructura de carpetas ya aparezca publicada.

## Parte 9: Flujo cotidiano de trabajo durante la cursada

A partir de la primera publicación, el flujo habitual será este:

```bash
git pull origin main
# editar o agregar archivos
git status
git add .
git commit -m "Mensaje descriptivo"
git push origin main
```

Regla de trabajo recomendada:

- antes de empezar una sesión de trabajo, ejecutá `git pull origin main` para traer cambios recientes;
- trabajá siempre dentro de la carpeta del tema o semana correspondiente;
- usá mensajes de commit claros y concretos.

Ejemplos de mensajes útiles:

- `Agregar notebook de introducción a python en la carpeta 001`
- `Subir PDF de la práctica de condicionales en la carpeta 002`
- `Actualizar ejercicios de funciones en la carpeta 003`
- `Corregir imágenes de apoyo de la clase 001`

## Parte 10: Cómo subir notebooks, imágenes, PDF y diapositivas

Este repositorio no guarda solo código. También funciona como carpeta ordenada de materiales de cursada.

Archivos que vas a usar con frecuencia:

- notebooks de Jupyter o Colab: `.ipynb`
- archivos de código tradicionales: `.py`, `.js`, `.cpp`, `.java`, etc.
- imágenes: `.png`, `.jpg`, `.jpeg`
- documentos: `.pdf`
- diapositivas: `.pdf`, `.pptx`

Recomendaciones por tipo de archivo:

### Notebooks y archivos de código

- si trabajaste en Google Colab, descargá el archivo `.ipynb` y guardalo en la carpeta del tema correspondiente en tu repositorio local;
- si usás código clásico, guardá tus scripts directamente en la carpeta correspondiente;
- revisá que el nombre del archivo sea claro y descriptivo;
- hacé `add`, `commit` y `push` igual que con cualquier otro material.

### Imágenes

- guardá capturas, esquemas o figuras dentro de la carpeta del tema correspondiente;
- evitá dejar imágenes sueltas fuera de contexto en la raíz del repositorio.

### PDF

- subí guías, apuntes exportados, informes o consignas cuando corresponda;
- el formato PDF se previsualiza muy bien directamente en GitHub.

### Diapositivas

- podés subir archivos `.pptx`, pero la vista previa puede variar según el navegador;
- si querés asegurar una lectura rápida y compatible con cualquier dispositivo, conviene subir también una versión en PDF.

Si lo necesitás, algunos archivos también pueden subirse desde la web de GitHub con la opción **Add file > Upload files**. Sin embargo, para mantener un flujo consistente y profesional, en esta guía priorizamos el trabajo con Git desde la terminal.

## Parte 11: Entregas por formulario y uso de enlaces

Cuando los docentes te pidan enviar un cuaderno o material por formulario, la entrega recomendada es el **enlace del archivo ya publicado en tu repositorio de GitHub**.

Esto evita varios problemas frecuentes:

- no tenés que comprimir archivos;
- no dependés de permisos manuales ni de accesibilidad en Google Colab;
- tu material queda respaldado en un entorno seguro y ordenado;
- los docentes pueden revisar exactamente la versión que publicaste en la fecha de entrega.

Procedimiento sugerido:

1. Abrí el archivo en GitHub una vez hecho el `push`.
2. Verificá que cargue y se renderice correctamente en la web.
3. Copiá la URL completa desde la barra de direcciones de tu navegador.
4. Pegá ese enlace en el formulario de entrega.

Si el formulario pide una entrega puntual, enviá el enlace directo al archivo. Si pide una revisión de todo tu progreso, podés enviar el enlace a la carpeta del tema o al repositorio completo.

## Parte 12: Ramas y pull requests en versión simplificada

En un repositorio personal de cursada, la mayor parte del tiempo vas a trabajar directamente sobre `main`. Eso alcanza para el flujo básico del curso.

Si en algún momento los docentes te piden trabajar con ramas (por ejemplo, para realizar correcciones aisladas o para un trabajo grupal), el esquema básico es este:

```bash
git switch -c correccion-tema-001
# realizar cambios
git add .
git commit -m "Corregir ejercicio del tema 001"
git push -u origin correccion-tema-001
```

Después podés abrir un **pull request (PR)** en GitHub. Un PR es una solicitud formal para incorporar cambios de una rama a otra, generalmente hacia la rama principal `main`.

Para esta guía, alcanza con que recuerdes dos ideas clave:

- `main` es tu rama principal de entrega y trabajo;
- una rama alternativa sirve para aislar cambios nuevos o correcciones antes de integrarlos a `main`.

## Parte 13: Troubleshooting básico

A continuación tenés algunos problemas frecuentes y su resolución.

### 1. `git` no se reconoce en la terminal

**Causa probable:** Git no se instaló correctamente o la terminal no se reinició.

**Solución:** reinstalá Git si hace falta y volvé a abrir la terminal. Luego ejecutá:

```bash
git --version
```

### 2. `Author identity unknown`

**Causa probable:** Git no tiene configurado tu nombre y tu correo.

**Solución:**

```bash
git config --global user.name "Tu Nombre y Apellido"
git config --global user.email "tu-correo@ejemplo.com"
```

### 3. `fatal: Authentication failed`

**Causa probable:** la autenticación con GitHub falló.

**Solución:**

- intentá iniciar sesión otra vez desde el flujo de autenticación de tu sistema;
- si GitHub te pide contraseña para `push`, no uses la contraseña común de tu cuenta: usá un **Personal Access Token** (PAT) o el método de autenticación SSH/web que GitHub te indique.

### 4. `! [rejected] main -> main (non-fast-forward)`

**Causa probable:** el repositorio remoto en GitHub tiene cambios que tu copia local todavía no incorporó.

**Solución:**

```bash
git pull origin main
git push origin main
```

### 5. La carpeta aparece en tu computadora pero no en GitHub

**Causa probable:** la carpeta estaba vacía o faltaron pasos del flujo Git.

**Solución:**

- agregá al menos un archivo dentro de la carpeta (o un `.gitkeep` si debe estar vacía temporalmente);
- ejecutá `git status` para revisar que Git detecte el cambio;
- después hacé `git add .`, `git commit` y `git push`.

### 6. El archivo existe localmente pero no se ve publicado

**Causa probable:** faltaron uno o más pasos entre `add`, `commit` y `push`.

**Solución:**

```bash
git status
git add .
git commit -m "Subir archivo faltante"
git push origin main
```

### 7. El enlace de Colab pide permisos

**Causa probable:** estás compartiendo el enlace directo de Google Colab y no el del archivo en GitHub, o tu repositorio en GitHub es privado.

**Solución:**

- priorizá compartir el enlace del archivo publicado en GitHub;
- configurá tu repositorio como público para que cualquier persona con el enlace pueda visualizarlo sin restricciones.

### 8. El repositorio tiene un nombre incorrecto

**Causa probable:** al crearlo no seguiste la convención de nomenclatura acordada.

**Solución recomendada:** corregilo cuanto antes. Si recién empezaste, conviene crear el repositorio correctamente en GitHub, clonarlo y mover el contenido. Si ya avanzaste bastante, también podés renombrarlo desde los ajustes en la web de GitHub y actualizar la URL remota en tu terminal local.

## Parte 14: Ejercicios prácticos

### Ejercicio 1: Crear el repositorio correcto

1. Creá un repositorio en GitHub respetando la convención de nomenclatura acordada.
2. Verificá que tenga el nombre correcto, visibilidad pública y un `README.md` inicial.

**Resultado esperado:** el repositorio existe en GitHub y tiene la estructura correcta.

---

### Ejercicio 2: Clonar y preparar tu primer tema

1. Cloná el repositorio en tu computadora.
2. Creá la carpeta de tu primer tema, por ejemplo: `001_intro_python`.
3. Agregá un archivo `.gitkeep` para que la carpeta no quede vacía al subirla.
4. Publicá los cambios con `git add .`, `git commit` y `git push`.

**Resultado esperado:** la carpeta del tema inicial aparece reflejada en GitHub.

---

### Ejercicio 3: Subir un notebook de Jupyter

1. Guardá un notebook `.ipynb` dentro de la carpeta `001_intro_python/`.
2. Publicalo usando el flujo clásico de Git (`add`, `commit`, `push`).
3. Verificá que puedas visualizarlo correctamente en tu repositorio remoto en GitHub.

**Resultado esperado:** el notebook se muestra de forma interactiva en la web de tu repositorio y posee su propia URL.

---

### Ejercicio 4: Subir material complementario

1. Agregá una imagen o un archivo PDF de apuntes en la misma carpeta o en una nueva (ej. `002_estructuras_control/`).
2. Publicá los cambios en GitHub.
3. Comprobá que los archivos se puedan abrir o descargar de manera directa.

**Resultado esperado:** el repositorio contiene diferentes tipos de materiales bien ordenados, listos para tu estudio.

---

### Ejercicio 5: Preparar una entrega por enlace

1. Desde la web de GitHub, navegá hasta el notebook o archivo que querés entregar.
2. Copiá la URL completa de tu navegador.
3. Compartí ese enlace en un documento, correo o formulario de entrega.

**Resultado esperado:** podés entregar enlaces completamente funcionales y legibles de tu trabajo sin comprimir archivos ni lidiar con permisos de acceso.

## Cierre y lista de verificación final

Antes de dar por terminado tu repositorio inicial, revisá esta lista:

- el nombre del repositorio cumple con la convención recomendada;
- la materia/curso, el período y el año son correctos en el nombre;
- la estructura utiliza carpetas secuenciales identificadas con tres dígitos y el tema descriptivo (ej. `001_intro_python`);
- todos tus archivos están organizados dentro del tema correspondiente;
- ejecutaste con éxito los pasos del flujo Git (`git add`, `git commit` y `git push`);
- verificaste en la web de GitHub que tus cambios y carpetas se ven correctamente;
- sabés cómo obtener y compartir el enlace de entrega directo de un archivo en GitHub.

Recursos útiles para profundizar:

- [Documentación oficial de Git](https://git-scm.com/doc)
- [Documentación oficial de GitHub](https://docs.github.com/)
- [GitHub Skills](https://skills.github.com/)

A partir de este punto, tu repositorio personal deja de ser una carpeta improvisada y pasa a ser una base ordenada para todas tus clases y proyectos futuros.
"""